/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mxg_io_SharedMemoryChannel */

#ifndef _Included_mxg_io_SharedMemoryChannel
#define _Included_mxg_io_SharedMemoryChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mxg_io_SharedMemoryChannel
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_mxg_io_SharedMemoryChannel_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     mxg_io_SharedMemoryChannel
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_mxg_io_SharedMemoryChannel_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     mxg_io_SharedMemoryChannel
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_mxg_io_SharedMemoryChannel_read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     mxg_io_SharedMemoryChannel
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mxg_io_SharedMemoryChannel_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
