/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssys_io_SharedMemoryChannel */

#ifndef _Included_com_ssys_io_SharedMemoryChannel
#define _Included_com_ssys_io_SharedMemoryChannel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssys_io_SharedMemoryChannel_WRITE
#define com_ssys_io_SharedMemoryChannel_WRITE 2L
#undef com_ssys_io_SharedMemoryChannel_READ
#define com_ssys_io_SharedMemoryChannel_READ 4L
#undef com_ssys_io_SharedMemoryChannel_CREATE
#define com_ssys_io_SharedMemoryChannel_CREATE 8L
#undef com_ssys_io_SharedMemoryChannel_PIPE
#define com_ssys_io_SharedMemoryChannel_PIPE 2L
#undef com_ssys_io_SharedMemoryChannel_BUFFER
#define com_ssys_io_SharedMemoryChannel_BUFFER 4L
/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    poll
 * Signature: ([I[I[IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_poll
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
