/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssys_io_SharedMemoryChannel */

#ifndef _Included_com_ssys_io_SharedMemoryChannel
#define _Included_com_ssys_io_SharedMemoryChannel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssys_io_SharedMemoryChannel_WRITE
#define com_ssys_io_SharedMemoryChannel_WRITE 2L
#undef com_ssys_io_SharedMemoryChannel_READ
#define com_ssys_io_SharedMemoryChannel_READ 4L
#undef com_ssys_io_SharedMemoryChannel_CREATE
#define com_ssys_io_SharedMemoryChannel_CREATE 8L
#undef com_ssys_io_SharedMemoryChannel_PIPE
#define com_ssys_io_SharedMemoryChannel_PIPE 2L
#undef com_ssys_io_SharedMemoryChannel_BUFFER
#define com_ssys_io_SharedMemoryChannel_BUFFER 4L
#undef com_ssys_io_SharedMemoryChannel_POLLIN
#define com_ssys_io_SharedMemoryChannel_POLLIN 1L
#undef com_ssys_io_SharedMemoryChannel_POLLOUT
#define com_ssys_io_SharedMemoryChannel_POLLOUT 4L
#undef com_ssys_io_SharedMemoryChannel_UNASSIGNED
#define com_ssys_io_SharedMemoryChannel_UNASSIGNED -1L
/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    implOpen
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_implOpen
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    implWrite
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_implWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    implRead
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_implRead
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ssys_io_SharedMemoryChannel
 * Method:    implClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemoryChannel_implClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
