/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssys_io_SharedMemorySelector */

#ifndef _Included_com_ssys_io_SharedMemorySelector
#define _Included_com_ssys_io_SharedMemorySelector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssys_io_SharedMemorySelector_UNASSIGNED
#define com_ssys_io_SharedMemorySelector_UNASSIGNED -1L
/*
 * Class:     com_ssys_io_SharedMemorySelector
 * Method:    getMaximumDescriptors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemorySelector_getMaximumDescriptors
  (JNIEnv *, jobject);

/*
 * Class:     com_ssys_io_SharedMemorySelector
 * Method:    poll
 * Signature: ([I[I[IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_ssys_io_SharedMemorySelector_poll
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ssys_io_SharedMemorySelector_ReadOnlySet */

#ifndef _Included_com_ssys_io_SharedMemorySelector_ReadOnlySet
#define _Included_com_ssys_io_SharedMemorySelector_ReadOnlySet
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
